### ISSUE TITLE
Pokemon Stats not lined up properly on English Language

### ISSUE THREAD

**Issue by Dynamixus** [ydarissep/PokeRogue-Pokedex#1]
As shown here:
![image](https://github.com/ydarissep/PokeRogue-Pokedex/assets/137287047/afb9f676-e077-4d32-87fd-47ad4ec3b546)

The ones from the other languages work fine, as far as I could tell. Tried clearing cache and using a different browser and all that.

**Comment by ydarissep** [comment]
Fixed
